export enum CaseType {
    CIVIL = 'CIVIL',
    CRIMINAL = 'CRIMINAL',
    COMMERCIAL = 'COMMERCIAL',
    ADMINISTRATIVE = 'ADMINISTRATIVE',
    SOCIAL = 'SOCIAL',
    LABOR = 'LABOR',
    FAMILY = 'FAMILY',
    LAND = 'LAND',
    CONSTITUTIONAL = 'CONSTITUTIONAL',
    MILITARY = 'MILITARY'
  }
  