export enum CaseType {
    CIVIL = 'CIVIL',
    CRIMINAL = 'CRIMINAL',
    COMMERCIAL = 'COMMERCIAL',
    ADMINISTRATIVE = 'ADMINISTRATIVE',
    SOCIAL = 'SOCIAL',
    LABOR = 'TRAVAIL',
    FAMILY = 'FAMILLE',
    LAND = 'IMMOBILIER',
    CONSTITUTIONAL = 'CONSTITUTIONNEL',
    MILITARY = 'MILITARY'
  }
  