export enum CourtType {
    FIRST_INSTANCE = 'FIRST_INSTANCE',
    HIGH = 'HIGH',
    APPEAL = 'APPEAL',
    CASSATION = 'CASSATION',
    ADMINISTRATIVE = 'ADMINISTRATIVE',
    LABOR = 'LABOR',
    COMMERCIAL = 'COMMERCIAL',
    FAMILY = 'FAMILY',
    MILITARY = 'MILITARY',
    ACCOUNTS = 'ACCOUNTS'
  }
  