export enum Governorate {
    Ariana = 'Ariana',
    Beja = 'Beja',
    BenArous = 'Ben Arous',
    Bizerte = 'Bizerte',
    Gabes = 'Gabes',
    Gafsa = 'Gafsa',
    Jendouba = 'Jendouba',
    Kairouan = 'Kairouan',
    Kasserine = 'Kasserine',
    Kebili = 'Kebili',
    Kef = 'Kef',
    Mahdia = 'Mahdia',
    Manouba = 'Manouba',
    Medenine = 'Medenine',
    Monastir = 'Monastir',
    Nabeul = 'Nabeul',
    Sfax = 'Sfax',
    SidiBouzid = 'Sidi Bouzid',
    Siliana = 'Siliana',
    Sousse = 'Sousse',
    Tataouine = 'Tataouine',
    Tozeur = 'Tozeur',
    Tunis = 'Tunis',
    Zaghouan = 'Zaghouan'
  }
  